#!/bin/bash
TMPFILE=`mktemp /tmp/${0##*/}.XXXXX`
trap 'rm -f $TMPFILE' 0
HWD=`cd "${0%/*}" >/dev/null 2>&1; echo $PWD`
#
ALL=""; LIST=""
while [ $# -gt 0 ]; do
  case "$1" in
    -a | all ) ALL="all"; shift ;;
    -d ) ALL="dangling"; shift ;;
    -? ) echo "Usage: ${0##*/} [-a|-d] [id/name ...]" 1>&2; exit 1 ;;
    * ) [ -n "$1" ] && LIST+=" $1"; shift ;;
  esac
done
[ -z "$LIST" -a -n "$ALL" ] && LIST=all
#
case "$ALL" in
# all ) docker images -a | awk -f "$HWD/dki.awk" > $TMPFILE
  dangling ) docker images -a -f dangling=true | awk -f "$HWD/dki.awk" > $TMPFILE ;;
  * ) docker images -a | awk -f "$HWD/dki.awk" > $TMPFILE ;;
esac
#
typeset -i RC=0
for dkn in $LIST; do
  while IFS= read -a A; do
    id=${A[0]}
    name=${A[1]}
    [ "$name" == "<none>" -o "$dkn" == "$id" ] && name=$id
    if [ "$dkn" == "$name" -o -n "$ALL" ]; then
      [ $RC -gt 0 ] && echo ""
      echo "Removing $name:"
      docker rmi -f $id
      [ $? -eq 0 ] && let RC=RC+1
    fi
  done < $TMPFILE
done
[ $RC -gt 0 ] && echo ""
echo "$RC images removed"
